name: Node.js CI/CD with NPM
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can adjust the version as needed
 
    - name: Install dependencies
      run: npm install

    - name: Install packages
      run: npm ci

    - name: Install mocha
      run: npm install -g mochawesome mochawesome-report-generator
      
    - name: unit test
      run: npm run test:unit --logger mochawesome.json

    - name: BDD test
      run: npm run test:bdd --logger "trx;LogFileName=bddtest.trx"

    - name: report
      run: cat	/home/runner/work/Unit/Unit/mochawesome-report/mochawesome.json

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        trx_files: "/home/runner/work/Unit/Unit/mochawesome-report/bddtest.trx"
